ALTER TABLE VEHICLE_KM_RECORDS DROP CONSTRAINT CK_KM_ODOMETER_ORDER;

ALTER TABLE VEHICLE_KM_RECORDS MODIFY ARRIVAL_ODOMETER NULL;

ALTER TABLE VEHICLE_KM_RECORDS ADD CONSTRAINT CK_KM_ODOMETER_ORDER
  CHECK (ARRIVAL_ODOMETER IS NULL OR ARRIVAL_ODOMETER >= DEPARTURE_ODOMETER);
